### ISSUE TITLE
Function redefinition

### ISSUE THREAD

**Issue by Mainuss** [trevorvanhoof/sqrmelon#14]
Hi Trevor.

I'm beginning to play with your LAST version.
After create a new project, create one shot immediately, I'm having some compilation "redefinition function" errors.

******************************************************************************************
Shader compile failure (0): 0(547) : error C1013: function "fLineSegment" is already defined at 0(486)
float fOctahedron(vec3 p,float r){return fGDF(p,r,3,6);}
float fTruncatedIcosahedron(vec3 p,float r){return fGDF(p,r,3,18);}

// Distance to line segment between <a> and <b>, used for fCapsule() version 2below
float fLineSegment(vec2 p, vec2 a, vec2 b) {
	vec2 ab = b - a;
	float t = sat(dot(p - a, ab) / dot(ab, ab));
	return length((ab * t + a) - p);
}
0(554) : error C1013: function "fCapsule" is already defined at 0(493)
	float t = sat(dot(p - a, ab) / dot(ab, ab));
	return length((ab * t + a) - p);
}

// Capsule version 2: between two end points <a> and <b> with radius r
float fCapsule(vec2 p, vec2 a, vec2 b, float r) {
	return fLineSegment(p, a, b) - r;
}

// Distance to line segment between <a> and <b>, used for fCapsule() version 2below
0(559) : error C1013: function "fLineSegment" is already defined at 0(498)
float fCapsule(vec2 p, vec2 a, vec2 b, float r) {
	return fLineSegment(p, a, b) - r;
}

// Distance to line segment between <a> and <b>, used for fCapsule() version 2below
float fLineSegment(vec3 p, vec3 a, vec3 b) {
	vec3 ab = b - a;
	float t = sat(dot(p - a, ab) / dot(ab, ab));
	return length((ab * t + a) - p);
}
0(566) : error C1013: function "fCapsule" is already defined at 0(505)
	float t = sat(dot(p - a, ab) / dot(ab, ab));
	return length((ab * t + a) - p);
}

// Capsule version 2: between two end points <a> and <b> with radius r
float fCapsule(vec3 p, vec3 a, vec3 b, float r) {
	return fLineSegment(p, a, b) - r;
}

// end hg_sdf
0(572) : error C1013: function "fOctahedron" is already defined at 0(542)
	return fLineSegment(p, a, b) - r;
}

// end hg_sdf

float fOctahedron(vec3 p, float r){return dot(abs(p),vec3(1.0))/sqrt(3)-r;}

// Engrave with round edges at the sides, like a soft material was pushed down by a thin object.
float fOpEngraveRound(float a,float b,float r){return max(a,min(r-abs(b),min(a+r,length(abs(vec2(a,b))-r)-r)));}

******************************************************************************************
Thanks for this awesome tool.
Main

PS: I don't have this error in a older version.

**Comment by trevorvanhoof** [comment]
You are correct sir, I just pushed a fix.

https://github.com/trevorvanhoof/sqrmelon/commit/d4260fb926a4e599718f6269db5211ceef6eefb7#diff-33d69292b73f5d0255ed0b10e80207bd

Note that you will have to delete and re-create a new project for this to work, project creation just copy pastes some files.

Alternatively you can copy over "sdf.glsl" to <your project>/Templates/default folder.
