### ISSUE TITLE
Saving the project causes a camera motion problem

### ISSUE THREAD

**Issue by androvisuals** [trevorvanhoof/sqrmelon#15]
Clicking save in the file menu causes the camera to keep moving backwards on the Z axis.
Windows 10.

**Comment by trevorvanhoof** [comment]
It's something to do with save having a shortcut (CTRL+S), and I think when you click it, it actually simulates a press of those buttons, never a release, so S is just left hanging there.

I thought about working around this by having an invisible CTRL+S action and a visible button without the shortcut, but then the CTRL +S hint in the menu disappears too. Maybe that is the lesser of 2 evils though.

**Comment by trevorvanhoof** [comment]
Still have not found a satisfying solution. Filing it as an annoying Qt bug that we'll just live with :')
