### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Mainuss** [trevorvanhoof/sqrmelon#16]
Hi trevor!
Missing any files on Player solution??
64k2Patch.h
64k2Song.h

Thanks in advance.

**Comment by trevorvanhoof** [comment]
Player/settings.h has some defines to select different audio implementations, including no audio.
It may be I have accidentally left some files in the solution that can be safely removed.

If you DO want to use 64klang2, please pop over to https://github.com/hzdgopher/64klang and get the latest files from there :)

**Comment by Mainuss** [comment]
Hi again Trevor.

Missing "Dialog.h" file when #define RESOLUTION_SELECTOR in main.cpp(428) for Player.sln ??

Thanks in advance.

**Comment by trevorvanhoof** [comment]
Sorry for getting back to this so late, submitted the dialog.rc/.h files and updated the readme about this :)
