### ISSUE TITLE
Error with exporting frames when loop time is not a whole number

### ISSUE THREAD

**Issue by androvisuals** [trevorvanhoof/sqrmelon#17]
I was working on making seamless loops which worked fine in sqrmelon but not in other video software.
I've discovered what the problem is.

Right clicking pin and then view on a shot in the shot manager to loop a shot doesn't set the correct duration.
In this screenshot the duration is 20 seconds

![image](https://user-images.githubusercontent.com/19530188/139048258-67b911bb-bb70-4313-936d-847ad1cebf52.png)

The actual time on the loop is set to 19.99

![image](https://user-images.githubusercontent.com/19530188/139048329-970fdc9a-a307-4fc2-a7c3-01bea89990c6.png)

When exporting the loop like this there is a very small but noticeable skip.
Manually setting it to the correct number, in this case 20 results in a perfect export which can be looped.

**Comment by androvisuals** [comment]
After discussing it we decided on....
"if we can have a flag saying we pinned a shot then we should be good to go, then its in loop mode so we use actual duration. If not we go back to dropping a frame so there's no glitch with going over to the next shot."

**Comment by trevorvanhoof** [comment]
Fixed by 55201ab080bb91e3178de3414a263804de4c4186
