### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Molive-0** [trevorvanhoof/sqrmelon#3]
Here are typos I've found:

On page 12 of the PDF, it claims you can double click the "shmsader" to open it. Presumably this is meant to say "shader".
On page 13 the info box ends with two stops. Also, the enable parenthesis don't close.
On page 17 there is no space between "values" and "this"

~Molive

**Comment by trevorvanhoof** [comment]
Thanks for your attention to detail! Just committed the changes :)
