### ISSUE TITLE
Missing cgmathx64.dll

### ISSUE THREAD

**Issue by tdhooper** [trevorvanhoof/sqrmelon#5]
It's looking for this dll that doesn't exist. Now, I barely know what a dll is, or how it's used, so feel free to ignore this and I'll go back to webgl land 😅

Is this something I have to build or get from somewhere? Or is this something which is fundamentally not gonna work on linux?

```
Traceback (most recent call last):
  File "/home/tdhooper/Projects/sqrmelon/SqrMelon/sceneview3d.py", line 164, in paintGL
    execfile(modifier, globals(), locals())
  File "/home/tdhooper/Projects/sqrmelon/SqrMelon/defaultproject/animationprocessor.py", line 2, in <module>
    cgmath.prepare()
  File "/home/tdhooper/Projects/sqrmelon/SqrMelon/cgmath/__init__.py", line 25, in prepare
    _dllHandle = ctypes.CDLL(dllPath)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/tdhooper/Projects/sqrmelon/SqrMelon/cgmath/cgmathx64.dll: invalid ELF header
```

**Comment by trevorvanhoof** [comment]
Ah, that's not gonna work indeed. A DLL is a compiled bundle of functions and it has to be compiled separately for linux / osx as their internals are different from windows. I can make a pure-python version that does not need the DLL, will keep you posted!

**Comment by tdhooper** [comment]
I looked into trying to compile it with gcc, but there's lots of Windows specific stuff in there isn't there?

Don't do that just yet, as I've not managed to get anything to draw yet so might not be worth it. Right now I'm running into a problem with setting up the buffers, I'll create another issue for that.

**Comment by trevorvanhoof** [comment]
I've made a try/except that will load a python version if the DLL load fails.
Also looked at your branch and tried to implement your fixes as much as I could. In theory you should be able to pull the master branch and be at the same point, give or take these 2 issues.
Probably you're not out of the woods yet but at least a lot closer!
