### ISSUE TITLE
hot reload python error

### ISSUE THREAD

**Issue by leon196** [trevorvanhoof/sqrmelon#7]
Hi Trevor, thanks for sharing your tool.
I've followed the instructions to install, but then it seems that changing files doesn't update the scene.
I've got this error:

> Traceback (most recent call last):
> File "D:\Shaders\SqrMelon\sqrmelon-master\SqrMelon\fileutil.py", line 71, in __forwardFileChanged
>     self.fileChanged.emit(path.replace('\\', '/'))
>   File "D:\Shaders\SqrMelon\sqrmelon-master\SqrMelon\qtutil.py", line 131, in emit
>     self.__connections[i](*args, **kwargs)
> TypeError: arguments did not match any overloaded call:
>   QWidget.repaint(): too many arguments
>   QWidget.repaint(int, int, int, int): argument 1 has unexpected type 'unicode'
>   QWidget.repaint(QRect): argument 1 has unexpected type 'unicode'
>   QWidget.repaint(QRegion): argument 1 has unexpected type 'unicode'
> Traceback (most recent call last):
>   File "D:\Shaders\SqrMelon\sqrmelon-master\SqrMelon\fileutil.py", line 71, in __forwardFileChanged
>     self.fileChanged.emit(path.replace('\\', '/'))
>   File "D:\Shaders\SqrMelon\sqrmelon-master\SqrMelon\qtutil.py", line 131, in emit
>     self.__connections[i](*args, **kwargs)
> TypeError: arguments did not match any overloaded call:
>   QWidget.repaint(): too many arguments
>   QWidget.repaint(int, int, int, int): argument 1 has unexpected type 'unicode'
>   QWidget.repaint(QRect): argument 1 has unexpected type 'unicode'
>   QWidget.repaint(QRegion): argument 1 has unexpected type 'unicode'

It's may be the Python installation that gone wrong? Did you already see this error?

**Comment by trevorvanhoof** [comment]
Hey, completely my bad, I've pushed a fix for this! Please let me know if it happens again after pulling, or if you spot anything else!
